### ISSUE TITLE
Seg fault with SaveTrackerHits

### ISSUE THREAD

**Issue by clementhelsens** [HEP-FCC/FCCSW#445]
Full sim example do not run out of the box if we do not comment lines like
https://github.com/HEP-FCC/FCCSW/blob/master/Examples/options/geant_fullsim_fccee_cld_pgun.py#L57

```
#6  0x00007f36acd651ff in SimG4SaveTrackerHits::saveOutput(G4Event const&) () from /cvmfs/sw.hsf.org/spackages2/k4simgeant4/0.1.0pre06/x86_64-centos7-gcc8.3.0-opt/cj3ygcddsvsrlpzhbwlkvsv2yiuuplod/lib/libSimG4Components.so
#7  0x00007f36acd343ad in SimG4Alg::execute() () from /cvmfs/sw.hsf.org/spackages2/k4simgeant4/0.1.0pre06/x86_64-centos7-gcc8.3.0-opt/cj3ygcddsvsrlpzhbwlkvsv2yiuuplod/lib/libSimG4Components.so
#8  0x00007f36c241991d in Gaudi::details::LegacyAlgorithmAdapter::execute (this=<optimized out>) at /tmp/gitlab-runner/spack-stage/spack-stage-gaudi-35.0-k5eyanlitmae6f4zggzpd5mvgklif3f4/spack-src/GaudiKernel/include/GaudiKernel/Algorithm.h:48
#9  0x00007f36c5fa3b17 in Gaudi::Algorithm::sysExecute (this=this
entry=0x1758b7d0, ctx=...) at /tmp/gitlab-runner/spack-stage/spack-stage-gaudi-35.0-k5eyanlitmae6f4zggzpd5mvgklif3f4/spack-src/GaudiKernel/src/Lib/Algorithm.cpp:367
#10 0x00007f36be086d20 in GaudiAlgorithm::sysExecute (this=0x1758b7d0, ctx=...) at /tmp/gitlab-runner/spack-stage/spack-stage-gaudi-35.0-k5eyanlitmae6f4zggzpd5mvgklif3f4/spack-src/GaudiAlg/src/lib/GaudiAlgorithm.cpp:117
#11 0x00007f36c6053d05 in MinimalEventLoopMgr::executeEvent (this=this
entry=0x2af0c30, context=...) at /tmp/gitlab-runner/spack-stage/spack-stage-gaudi-35.0-k5eyanlitmae6f4zggzpd5mvgklif3f4/spack-src/GaudiKernel/src/Lib/MinimalEventLoopMgr.cpp:352
#12 0x00007f36c23af013 in EventLoopMgr::executeEvent (this=0x2af0c30, ctx=...) at /tmp/gitlab-runner/spack-stage/spack-stage-gaudi-35.0-k5eyanlitmae6f4zggzpd5mvgklif3f4/spack-src/GaudiCoreSvc/src/ApplicationMgr/EventLoopMgr.cpp:259
#13 0x00007f36c23b0a99 in EventLoopMgr::nextEvent (this=0x2af0c30, maxevt=2) at /tmp/gitlab-runner/spack-stage/spack-stage-gaudi-35.0-k5eyanlitmae6f4zggzpd5mvgklif3f4/spack-src/GaudiCoreSvc/src/ApplicationMgr/EventLoopMgr.cpp:341
#14 0x00007f36c605201d in MinimalEventLoopMgr::executeRun (this=<optimized out>, maxevt=<optimized out>) at /tmp/gitlab-runner/spack-stage/spack-stage-gaudi-35.0-k5eyanlitmae6f4zggzpd5mvgklif3f4/spack-src/GaudiKernel/src/Lib/MinimalEventLoopMgr.cpp:306
#15 0x00007f36c2380548 in ApplicationMgr::executeRun (this=0x107a1a0, evtmax=2) at /tmp/gitlab-runner/spack-stage/spack-stage-gaudi-35.0-k5eyanlitmae6f4zggzpd5mvgklif3f4/spack-src/GaudiCoreSvc/src/ApplicationMgr/ApplicationMgr.cpp:833
#16 0x00007f36c5fc88de in Gaudi::Application::run (this=0x1076900) at /tmp/gitlab-runner/spack-stage/spack-stage-gaudi-35.0-k5eyanlitmae6f4zggzpd5mvgklif3f4/spack-src/GaudiKernel/src/Lib/Application.cpp:87
#17 0x00007f36c7a1fdbd in ffi_call_unix64 () from /cvmfs/sw.hsf.org/spackages/linux-centos7-x86_64/gcc-8.3.0/libffi-3.3-4fasf5o6ydxrggis5nzlenkfz3itt5bw/lib64/libffi.so.7
#18 0x00007f36c7a1ef87 in ffi_call_int () from /cvmfs/sw.hsf.org/spackages/linux-centos7-x86_64/gcc-8.3.0/libffi-3.3-4fasf5o6ydxrggis5nzlenkfz3itt5bw/lib64/libffi.so.7
#19 0x00007f36c7c349ea in _call_function_pointer (argcount=1, resmem=0x7ffecc19c4b0, restype=<optimized out>, atypes=<optimized out>, avalues=0x7ffecc19c4a0, pProc=0x7f36c5fc66d0 <_py_Gaudi__Application__run(Gaudi::Application*)>, flags=4357) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Modules/_ctypes/callproc.c:829
#20 _ctypes_callproc (pProc=pProc
entry=0x7f36c5fc66d0 <_py_Gaudi__Application__run(Gaudi::Application*)>, argtuple=argtuple
entry=0x7f36c7175950, flags=4357, argtypes=argtypes
entry=0x7f36c7175990, restype=restype
entry=0xa47920, checker=0x0) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Modules/_ctypes/callproc.c:1201
#21 0x00007f36c7c2cc45 in PyCFuncPtr_call (self=<optimized out>, inargs=<optimized out>, kwds=0x0) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Modules/_ctypes/_ctypes.c:4025
#22 0x00007f36c98d07c3 in _PyObject_FastCallKeywords (callable=0x7f36c70d7a10, stack=<optimized out>, nargs=<optimized out>, kwnames=0x0) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Objects/call.c:199
#23 0x00007f36c98ab0fd in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Python/ceval.c:4619
#24 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Python/ceval.c:3093
#25 0x00007f36c98a438b in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Objects/call.c:283
#26 0x00007f36c98d0207 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Objects/call.c:415
#27 0x00007f36c98aceb5 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Python/ceval.c:4616
#28 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Python/ceval.c:3110
#29 0x00007f36c98a438b in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=2, globals=<optimized out>) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Objects/call.c:283
#30 0x00007f36c98d0207 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Objects/call.c:415
#31 0x00007f36c98aceb5 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Python/ceval.c:4616
#32 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Python/ceval.c:3110
#33 0x00007f36c99a6bce in _PyEval_EvalCodeWithName (_co=0x7f36c70c7150, globals=<optimized out>, locals=locals
entry=0x0, args=<optimized out>, argcount=3, kwnames=0x0, kwargs=0x8d5258, kwcount=0, kwstep=1, defs=0x7f36c717fe28, defcount=1, kwdefs=0x0, closure=0x0, name=0x7f36c9edc770, qualname=0x7f36c717fab0) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Python/ceval.c:3930
#34 0x00007f36c98d00e3 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Objects/call.c:433
#35 0x00007f36c98aceb5 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /tmp/gitlab-runner/spack-stage/spack-stage-python-3.7.8-frt23dg2wxsliomspjt5yyg6attakzgk/spack-src/Python/ceval.c:4616
```

**Comment by vvolkl** [comment]
This is a consequence of https://github.com/HEP-FCC/FCCDetectors/issues/11 - since the sensitive detectors are there several times in the stack, it depends on the order in the LD_LIBRARY_PATH which one dd4hep picks up. It turns out that the order is wrong (lcgeo comes first) by default, so while the code is not reorganized I have to manually patch the setup script. Should be fixed for the current one.

**Comment by clementhelsens** [comment]
thanks @vvolkl !
