### ISSUE TITLE
Example/test fails

### ISSUE THREAD

**Issue by atolosadelgado** [HEP-FCC/FCCSW#478]
Hi,

it seems there is an example/test that is making the k4geo PR fail [1],

```
 6/17 Test  #9: geant_fullsim_fccee_lar_pgun.py ......***Failed    2.72 sec
Traceback (most recent call last):
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2024-09-04/x86_64-almalinux9-gcc11.4.1-opt/k4fwcore/ddd3ff32aec0e56e8e9b9d774dc417386a87d352_develop-6qih7r/bin/k4run", line 241, in <module>
    main()
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2024-09-04/x86_64-almalinux9-gcc11.4.1-opt/k4fwcore/ddd3ff32aec0e56e8e9b9d774dc417386a87d352_develop-6qih7r/bin/k4run", line 185, in main
    load_file(file)
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2024-09-04/x86_64-almalinux9-gcc11.4.1-opt/k4fwcore/ddd3ff32aec0e56e8e9b9d774dc417386a87d352_develop-6qih7r/python/k4FWCore/utils.py", line 51, in load_file
    exec(code, globals())
  File "geant_fullsim_fccee_lar_pgun.py", line 278, in <module>
    from Configurables import EventCounter
ImportError: cannot import name 'EventCounter' from 'Gaudi.Configurables' (unknown location)
```

[1] https://github.com/key4hep/k4geo/actions/runs/10720787324/job/29727802220?pr=381#step:3:1284

**Comment by BrieucF** [comment]
Yes, this is because Key4hep does no longer build  GaudiAlgs. I am not sure if there is a workaround but for the test it is enough to just remove the event_counter.

**Comment by atolosadelgado** [comment]
After removing "EventCounter" in line 16, new errors appear:

```
CreateECalBarre...  ERROR Missing cellID encoding for input collection
EventLoopMgr        ERROR Unable to initialize Algorithm: CreateECalBarrelCellsStep1
ServiceManager      ERROR Unable to initialize Service: EventLoopMgr
ApplicationMgr      ERROR Application Manager Terminated with error code 1
```
